### ISSUE TITLE
No version found for react/http

### ISSUE THREAD

**Issue by back-2-95** [phly/react2psr7#2]
Could not find dev version from react/http which satisfies this. Has reactphp libraries changed since your [blog post](https://mwop.net/blog/2016-04-17-react2psr7.html)

Tried with this and also with hand made composer.json:

`composer require "react/http:^0.5@dev" phly/react2psr7`  

```
Problem 1
    - The requested package react/http ^0.5@dev exists as react/http[0.3.x-dev, dev-WyriHaximus-php7-hhvm-travis, dev-compat-guzzle-deps, dev-master, dev-streaming-multipart, v0.1.0, v0.1.1, v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.6, v0.3.0, v0.4.0, v0.4.1] but these are rejected by your constraint.
  Problem 2
    - Installation request for phly/react2psr7 0.1.1 -> satisfiable by phly/react2psr7[0.1.1].
    - phly/react2psr7 0.1.1 requires react/http ^0.5@dev -> no matching package found.
```

**Comment by 4orever** [comment]
The same problem. There is no such version in repo.

**Comment by koflerdavid** [comment]
Try to alias `dev-master` of react/http to version 0.5, i.e., `"react/http": "dev-master as 0.5"`. I think this is what the Readme tries to say in the installation section.

**Comment by andig** [comment]
> Try to alias dev-master of react/http to version 0.5, i.e., "react/http": "dev-master as 0.5". I think this is what the Readme tries to say in the installation section.

Imho not working. Neither `master` nor `0.5` seem to have the require `getFiles()`or `getBody()`methods. Too bad, but imho not usable right now?

**Comment by weierophinney** [comment]
@andig, @back-2-95, et al: React has changed since I wrote the blog post, and this is the danger of creating a library against something pre-1.0.

I'll see if I can identify what needs to change in order to make this work.

**Comment by andig** [comment]
Might make sense to wait for 0.5 or 0.5.1- it recently seems to have gaind some traction again ;)

**Comment by weierophinney** [comment]
Ugh... the changes to remove `getFiles()` and `getBody()` mean that this library will likely require a parser of some sort, which I was hoping to avoid. I'll wait and see if they re-introduce those methods before doing too much work here.
